### ISSUE TITLE
Setup DB migration via ENV vars/etc?

### ISSUE THREAD

**Issue by 0xdevalias** [blacklabelops/crucible#2]
It might be more effort than it's worth since you only need to manually configure it once, but it would be kind of cool if I could define that I will be useing postgres in my `docker-compose.yml` env vars, and then have it automagically [call the command line tool to set it up](https://confluence.atlassian.com/fisheye/migrating-to-postgresql-298976837.html#MigratingtoPostgreSQL-Option2:Migrateusingthecommandline).

**Comment by blacklabelops** [comment]
Yes, that would be fantastic. But without the manual configuration there is nothing inside the database to migrate. When should I trigger it?

You can already call the command line tool:

~~~~
$ docker exec -it <yourcontainername> /opt/crucible/bin/fisheyectl.sh
~~~~

**Comment by 0xdevalias** [comment]
Hrmm.. I definitely haven't looked too deeply into it, but my motivation is that "i want it to run on postgres", thus it should be possible to do that from the start.

I would imagine that even without any data in there, you could 'migrate' it to use postgres from the beginning, and then when data is added it would use the new DB, but I haven't looked too deeply at that.

**Comment by blacklabelops** [comment]
According to this Atlassian documentation, the official way is to install fisheye/crucible and then migrate to postgres: https://confluence.atlassian.com/fisheye/migrating-to-postgresql-298976837.html.  There is no official way to start this prior installation or during installation.

I can think only of the following steps:

1. Start the container and install fisheye
1. Restart the container and trigger the migration by console
1. Restart the container again without the migration parameter

Actually the UI is much easier to handle to such a complicated workflow.

**Comment by 0xdevalias** [comment]
Yeah.. that does seem kind of hacky. I guess it's not a massive issue since it's only a one time setup.

Thanks for looking into it :)
